In [13]:
import pandas as pd
import os
import glob

In [50]:
path = 'D:\Tutorials\SDST\My Projects\Capstone3\datasets'
all_tokens = glob.glob(os.path.join(path, '*.csv'))
df = pd.concat([pd.read_csv(t) for t in all_tokens])

In [52]:
prefixes = ['BTC', 'ETH', 'DOT', 'XRP', 'ADA', 'LINK', 'LTC', 'XLM', 'XMR', 'XTZ']
for p in prefixes:
    df = df.add_prefix(p)

In [53]:
df

,XTZXMRXLMLTCLINKADAXRPDOTETHBTCDate,XTZXMRXLMLTCLINKADAXRPDOTETHBTCOpen,XTZXMRXLMLTCLINKADAXRPDOTETHBTCHigh,XTZXMRXLMLTCLINKADAXRPDOTETHBTCLow,XTZXMRXLMLTCLINKADAXRPDOTETHBTCClose,XTZXMRXLMLTCLINKADAXRPDOTETHBTCVolume,XTZXMRXLMLTCLINKADAXRPDOTETHBTCMarket Cap
0,2020-12-12,18051.32,18919.55,18046.04,18803.66,2.175258e+10,3.491706e+11
1,2020-12-11,18263.93,18268.45,17619.53,18058.90,2.791964e+10,3.353262e+11
2,2020-12-10,18553.30,18553.30,17957.07,18264.99,2.554713e+10,3.391369e+11
3,2020-12-09,18320.88,18626.29,17935.55,18553.92,3.442037e+10,3.444865e+11
4,2020-12-08,19191.53,19283.48,18269.95,18321.14,3.169229e+10,3.401488e+11
...,...,...,...,...,...,...,...
2780,2013-05-03,3.39,3.45,2.40,3.04,0.000000e+00,5.269485e+07
2781,2013-05-02,3.78,4.04,3.01,3.37,0.000000e+00,5.828798e+07
2782,2013-05-01,4.29,4.36,3.52,3.80,0.000000e+00,6.560460e+07
2783,2013-04-30,4.40,4.57,4.17,4.30,0.000000e+00,7.402092e+07
2784,2013-04-29,4.37,4.57,4.23,4.38,0.000000e+00,7.538896e+07

In [79]:
df_bitcoin = pd.read_csv('../datasets/1.bitcoin.csv')
df_bitcoin.head()
df_bitcoin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2785 entries, 0 to 2784
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        2785 non-null   object
 1   Open        2785 non-null   float64
 2   High        2785 non-null   float64
 3   Low         2785 non-null   float64
 4   Close       2785 non-null   float64
 5   Volume      2785 non-null   float64
 6   Market Cap  2785 non-null   float64
dtypes: float64(6), object(1)
memory usage: 152.4+ KB

In [80]:
df_eth = pd.read_csv('../datasets/2.ethereum.csv')
df_eth.head()
df_eth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1955 entries, 0 to 1954
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        1955 non-null   object
 1   Open        1955 non-null   float64
 2   High        1955 non-null   float64
 3   Low         1955 non-null   float64
 4   Close       1955 non-null   float64
 5   Volume      1955 non-null   float64
 6   Market Cap  1955 non-null   float64
dtypes: float64(6), object(1)
memory usage: 107.0+ KB

In [28]:
df_1 = pd.concat([pd.read_csv(t) for t in all_tokens], axis=1)

In [29]:
df_1

,Date,Open,High,Low,Close,Volume,Market Cap,Date,Open,High,...,Close,Volume,Market Cap,Date,Open,High,Low,Close,Volume,Market Cap
0,2020-12-12,18051.32,18919.55,18046.04,18803.66,2.175258e+10,3.491706e+11,2020-12-12,0.139423,0.147259,...,2.13,115337158.0,1.607668e+09,2020-12-12,0.546316,0.546316,0.487353,0.506401,1.092506e+10,2.299263e+10
1,2020-12-11,18263.93,18268.45,17619.53,18058.90,2.791964e+10,3.353262e+11,2020-12-11,0.142022,0.142694,...,2.08,132572049.0,1.567760e+09,2020-12-11,0.573062,0.583693,0.531383,0.546483,1.070820e+10,2.481254e+10
2,2020-12-10,18553.30,18553.30,17957.07,18264.99,2.554713e+10,3.391369e+11,2020-12-10,0.148170,0.148530,...,2.11,116436665.0,1.586356e+09,2020-12-10,0.583657,0.586856,0.556169,0.572954,9.695433e+09,2.598623e+10
3,2020-12-09,18320.88,18626.29,17935.55,18553.92,3.442037e+10,3.444865e+11,2020-12-09,0.140942,0.149810,...,2.17,195559316.0,1.636140e+09,2020-12-09,0.558667,0.601939,0.505983,0.583590,1.264857e+10,2.646860e+10
4,2020-12-08,19191.53,19283.48,18269.95,18321.14,3.169229e+10,3.401488e+11,2020-12-08,0.154127,0.154936,...,2.15,201313793.0,1.619736e+09,2020-12-08,0.608858,0.610161,0.554570,0.558836,8.302771e+09,2.534592e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2780,2013-05-03,106.25,108.13,79.10,97.75,0.000000e+00,1.085995e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2781,2013-05-02,116.38,125.60,92.28,105.21,0.000000e+00,1.168517e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2782,2013-05-01,139.00,139.89,107.72,116.99,0.000000e+00,1.298955e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2783,2013-04-30,144.00,146.93,134.05,139.00,0.000000e+00,1.542813e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2784,2013-04-29,134.44,147.49,134.00,144.54,0.000000e+00,1.603769e+09,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df['Date'] = pd.to_datetime(df['Date'])

In [41]:
df

,Date,Open,High,Low,Close,Volume,Market Cap
0,2020-12-12,18051.320000,18919.550000,18046.040000,18803.660000,2.175258e+10,3.491706e+11
1,2020-12-11,18263.930000,18268.450000,17619.530000,18058.900000,2.791964e+10,3.353262e+11
2,2020-12-10,18553.300000,18553.300000,17957.070000,18264.990000,2.554713e+10,3.391369e+11
3,2020-12-09,18320.880000,18626.290000,17935.550000,18553.920000,3.442037e+10,3.444865e+11
4,2020-12-08,19191.530000,19283.480000,18269.950000,18321.140000,3.169229e+10,3.401488e+11
...,...,...,...,...,...,...,...
2683,2013-08-08,0.004397,0.004424,0.004175,0.004254,0.000000e+00,3.325863e+07
2684,2013-08-07,0.004669,0.004682,0.004333,0.004417,0.000000e+00,3.453412e+07
2685,2013-08-06,0.005637,0.005661,0.004629,0.004680,0.000000e+00,3.659101e+07
2686,2013-08-05,0.005875,0.005980,0.005613,0.005613,0.000000e+00,4.387916e+07
2687,2013-08-04,0.005874,0.005927,0.005874,0.005882,0.000000e+00,4.598358e+07

In [73]:
all_files = glob.glob(os.path.join(path, '*.csv'))

li = []

for filename in all_files:
    df = pd.read_csv(filename)
    li.append(df)

frame = pd.concat(li, axis=1, keys=[p for p in prefixes])

In [76]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2785 entries, 0 to 2784
Data columns (total 70 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   (BTC, Date)         2785 non-null   object
 1   (BTC, Open)         2785 non-null   float64
 2   (BTC, High)         2785 non-null   float64
 3   (BTC, Low)          2785 non-null   float64
 4   (BTC, Close)        2785 non-null   float64
 5   (BTC, Volume)       2785 non-null   float64
 6   (BTC, Market Cap)   2785 non-null   float64
 7   (ETH, Date)         2322 non-null   object
 8   (ETH, Open)         2322 non-null   float64
 9   (ETH, High)         2322 non-null   float64
 10  (ETH, Low)          2322 non-null   float64
 11  (ETH, Close)        2322 non-null   float64
 12  (ETH, Volume)       2322 non-null   float64
 13  (ETH, Market Cap)   2322 non-null   float64
 14  (DOT, Date)         2397 non-null   object
 15  (DOT, Open)         2397 non-null   float64
 16  (DOT, High)         2397 non-null   float64
 17  (DOT, Low)          2397 non-null   float64
 18  (DOT, Close)        2397 non-null   float64
 19  (DOT, Volume)       2397 non-null   float64
 20  (DOT, Market Cap)   2397 non-null   float64
 21  (XRP, Date)         1168 non-null   object
 22  (XRP, Open)         1168 non-null   float64
 23  (XRP, High)         1168 non-null   float64
 24  (XRP, Low)          1168 non-null   float64
 25  (XRP, Close)        1168 non-null   float64
 26  (XRP, Volume)       1168 non-null   float64
 27  (XRP, Market Cap)   1168 non-null   float64
 28  (ADA, Date)         1955 non-null   object
 29  (ADA, Open)         1955 non-null   float64
 30  (ADA, High)         1955 non-null   float64
 31  (ADA, Low)          1955 non-null   float64
 32  (ADA, Close)        1955 non-null   float64
 33  (ADA, Volume)       1955 non-null   float64
 34  (ADA, Market Cap)   1955 non-null   float64
 35  (LINK, Date)        115 non-null    object
 36  (LINK, Open)        115 non-null    float64
 37  (LINK, High)        115 non-null    float64
 38  (LINK, Low)         115 non-null    float64
 39  (LINK, Close)       115 non-null    float64
 40  (LINK, Volume)      115 non-null    float64
 41  (LINK, Market Cap)  115 non-null    float64
 42  (LTC, Date)         2688 non-null   object
 43  (LTC, Open)         2688 non-null   float64
 44  (LTC, High)         2688 non-null   float64
 45  (LTC, Low)          2688 non-null   float64
 46  (LTC, Close)        2688 non-null   float64
 47  (LTC, Volume)       2688 non-null   float64
 48  (LTC, Market Cap)   2688 non-null   float64
 49  (XLM, Date)         1169 non-null   object
 50  (XLM, Open)         1169 non-null   float64
 51  (XLM, High)         1169 non-null   float64
 52  (XLM, Low)          1169 non-null   float64
 53  (XLM, Close)        1169 non-null   float64
 54  (XLM, Volume)       1169 non-null   float64
 55  (XLM, Market Cap)   1169 non-null   float64
 56  (XMR, Date)         1180 non-null   object
 57  (XMR, Open)         1180 non-null   float64
 58  (XMR, High)         1180 non-null   float64
 59  (XMR, Low)          1180 non-null   float64
 60  (XMR, Close)        1180 non-null   float64
 61  (XMR, Volume)       1180 non-null   float64
 62  (XMR, Market Cap)   1180 non-null   float64
 63  (XTZ, Date)         2785 non-null   object
 64  (XTZ, Open)         2785 non-null   float64
 65  (XTZ, High)         2785 non-null   float64
 66  (XTZ, Low)          2785 non-null   float64
 67  (XTZ, Close)        2785 non-null   float64
 68  (XTZ, Volume)       2785 non-null   float64
 69  (XTZ, Market Cap)   2785 non-null   float64
dtypes: float64(60), object(10)
memory usage: 1.5+ MB